# Generated by Django 4.2.2 on 2023-06-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='yayasan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
